atl_ranks.all_ranks = {
    beginner = {description = "[Beginner]", color = "#42b0ee", min_level = 1, max_level = 3},
    apprentice = {description = "[Apprentice]", color = "#2aa5eb", min_level = 4, max_level = 6},
    novice = {description = "[Novice]", color = "#0697ea", min_level = 7, max_level = 10},
    intermediate = {description = "[Intermediate]", color = "#0987cf", min_level = 11, max_level = 14},
    advanced = {description = "[Advanced]", color = "#097abb", min_level = 15, max_level = 18},
    expert = {description = "[Expert]", color = "#17db0c", min_level = 19, max_level = 22},
    lord = {description = "[Lord]", color = "#f7dd05", min_level = 23, max_level = 30},
    legend = {description = "[Legend]", color = "#d81313", min_level = 31, max_level = 45},

    admin = {description = "[Admin]", color = "#d81313"},
    developer = {description = "[Developer]", color = "#356aaa"},
}

atl_ranks.exp_table = {
    {block = "default:stone_with_coal", exp = 1},
    {block = "default:stone_with_copper", exp = 2},
    {block = "default:stone_with_tin", exp = 2},
    {block = "default:stone_with_iron", exp = 3},
    {block = "default:stone_with_mese", exp = 5},
    {block = "default:stone_with_gold", exp = 5},
    {block = "default:stone_with_diamond", exp = 7},
}

atl_ranks.lootbox_items = {
    {"default:diamond", quantity = math.random(10,30)},
    {"default:stone", quantity = math.random(100,230)},
    {"default:mese_crystal", quantity = math.random(20,60)},
    {"default:steel_ingot", quantity = math.random(30,99)},
    {"currency:minegeld_50", quantity = math.random(15,40)},
    {"x_obsidianmese:sword", quantity = math.random(1,4)},
    {"x_obsidianmese:chest", quantity = math.random(1,3)},
    {"xdecor:enchantment_table", quantity = math.random(1,5)},
    {"travelnet:travelnet", quantity = math.random(3,10)},
    {"tnt:tnt_stick", quantity = math.random(10,87)},
    {"unified_inventory:bag_large", quantity = math.random(1,6)},
    {"farming:bread", quantity = math.random(30,99)},
    {"simple_farming:corn", quantity = math.random(15,40)},
    {"simple_farming:carrot", quantity = math.random(10,30)},
    {"simple_farming:melon", quantity = math.random(20,60)},
    {"simple_farming:tomato", quantity = math.random(30,99)},
    {"moreores:mithril_ingot", quantity = math.random(15,20)},
    {"mobs:lava_orb", quantity = math.random(10,30)},
    {"mobs:meat", quantity = math.random(20,60)},
    {"legendary_armor:ingot", quantity = math.random(1,4)},
    {"farming:wheat", quantity = math.random(15,120)},
    {"farming:cotton", quantity = math.random(10,100)},
    {"gravelsieve:auto_sieve3", quantity = math.random(1,12)},
    {"deepslate:deepslate", quantity = math.random(32,123)},
    {"default:obsidian", quantity = math.random(15,90)},
    {"legendary_armor:sword", quantity = math.random(1,1)},
    {"default:copper_ingot", quantity = math.random(10,100)},
    {"default:tin_ingot", quantity = math.random(10,100)},
    {"default:bronze_ingot", quantity = math.random(10,100)},
    {"default:gold_ingot", quantity = math.random(10,100)},
    {"moreores:silver_ingot", quantity = math.random(10,100)},
    {"default:glass", quantity = math.random(10,100)},
}
